using System.Collections.Generic;

namespace Haptic.Gameplay
{
    public static class LevelCatalog
    {
        public static IReadOnlyList<LevelDefinition> Levels { get; } = new[]
        {
            new LevelDefinition("FIRST CONTACT", "WALL", false, TutorialPattern.Wall,
                "#######",
                "#S....#",
                "#####.#",
                "#E....#",
                "#######"),
            new LevelDefinition("THE SIGNAL", "FOLLOW", false, TutorialPattern.Goal,
                "#########",
                "#S#.....#",
                "#.#.###.#",
                "#...#E..#",
                "#########"),
            new LevelDefinition("BROKEN RHYTHM", "DANGER", false, TutorialPattern.Trap,
                "#########",
                "#S......#",
                "#.#####.#",
                "#..T..#.#",
                "#####.#E#",
                "#.......#",
                "#########"),
            new LevelDefinition("TWIN ECHO", "KEY", true, TutorialPattern.Key,
                "#########",
                "#S..#..E#",
                "#.#.#.#.#",
                "#.#...#.#",
                "#.#####.#",
                "#.....K.#",
                "#########"),
            new LevelDefinition("VEIL", "LISTEN", false, TutorialPattern.None,
                "###########",
                "#S#.......#",
                "#.#.#####.#",
                "#.#.....#.#",
                "#.#####.#.#",
                "#.....#.#E#",
                "#####.#.#.#",
                "#.......#.#",
                "###########"),
            new LevelDefinition("FAULTLINE", "AVOID", false, TutorialPattern.None,
                "###########",
                "#S....#...#",
                "#####.#.#.#",
                "#...#...#.#",
                "#.#T#####.#",
                "#.#.....#.#",
                "#.#####.#E#",
                "#.........#",
                "###########"),
            new LevelDefinition("RESONANCE", "RETURN", true, TutorialPattern.None,
                "#############",
                "#S....#.....#",
                "#.###.#.###.#",
                "#...#...#K#.#",
                "###.#####.#.#",
                "#...#.....#.#",
                "#.###.#####.#",
                "#.........#E#",
                "#############"),
            new LevelDefinition("STATIC", "ENDURE", false, TutorialPattern.None,
                "#############",
                "#S#.....#...#",
                "#.#.###.#.#.#",
                "#...#T#...#.#",
                "#####.#####.#",
                "#.....#.....#",
                "#.#####.###.#",
                "#.......#TE.#",
                "#############"),
            new LevelDefinition("UNDERTOW", "DESCEND", true, TutorialPattern.None,
                "###############",
                "#S....#.......#",
                "#.###.#.#####.#",
                "#.#...#.....#.#",
                "#.#.#######.#.#",
                "#.#.....T.#.#.#",
                "#.#####.#.#.#.#",
                "#...K...#...#.#",
                "###.#########.#",
                "#...........#E#",
                "###############"),
            new LevelDefinition("ABSOLUTION", "REMEMBER", true, TutorialPattern.None,
                "#################",
                "#S#.....#.......#",
                "#.#.###.#.#####.#",
                "#...#.#...#...#.#",
                "#####.#####.#.#.#",
                "#.........#.#...#",
                "#.#.#####.#.###.#",
                "#.#...T.#.#...#.#",
                "#.#####.#.###.#.#",
                "#.....#.#K..#.#.#",
                "#.###.#.#####.#.#",
                "#...#.........#E#",
                "#################")
        };
    }
}

